services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: platform-network # Assuming there's a shared network for BE

